### ISSUE TITLE
Issue on Android Marshmallow

### ISSUE THREAD

**Issue by pylerSM** [pylerSM/XInternalSD#14]
```
11-15 13:39:57.034 E/Xposed  (  344): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] android.content.pm.IPackageManager.getPackagesForUid(int)' on a null object reference
11-15 13:39:57.034 E/Xposed  (  344): 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:872)
11-15 13:39:57.034 E/Xposed  (  344): 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:85)
11-15 13:39:57.034 E/Xposed  (  344): 	at android.os.Environment.getExternalStorageDirectory(Environment.java:348)
11-15 13:39:57.034 E/Xposed  (  344): 	at com.pyler.xinternalsd.XInternalSD.initZygote(XInternalSD.java:117)
11-15 13:39:57.034 E/Xposed  (  344): 	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:483)
11-15 13:39:57.034 E/Xposed  (  344): 	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:432)
11-15 13:39:57.034 E/Xposed  (  344): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-15 13:40:04.926 E/Xposed  ( 1248): java.lang.IllegalStateException: Service user.xposed.app does not exist
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.services.BinderService.<init>(BinderService.java:162)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.services.BinderService.getService(BinderService.java:26)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.SELinuxHelper.initForProcess(SELinuxHelper.java:65)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:206)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at com.android.server.SystemServer.run(SystemServer.java:292)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at com.android.server.SystemServer.main(SystemServer.java:179)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at java.lang.reflect.Method.invoke(Native Method)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-15 13:40:04.926 E/Xposed  ( 1248): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by pylerSM** [comment]
Possible fix, need to verify it whether it works on not: https://github.com/pylerSM/XInternalSD/commit/f2c5bfe39b0081e2ebc874bbe109188f1895d229

**Comment by cloud9350** [comment]
It's work? : [af1268e](http://github.com/pylerSM/XInternalSD/commit/af1268eacc277826ca970f948453331a05e9b65b)

**Comment by pylerSM** [comment]
Yes, test build is on XDA thread

**Comment by cloud9350** [comment]
@pylerSM Thanks. :smile:
